services:
  identity-db:
    container_name: e-commerce-identity-postgres
    image: postgres:17.5
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: identity_user
      POSTGRES_PASSWORD: identity_password
      POSTGRES_DB: identity_db
    volumes:
      - identity-db-data:/var/lib/postgresql/data

volumes:
  identity-db-data: